version: '3'
services:
  authentication:
    env_file:
      - .env
    build:
      context: ./authentication
    ports:
      - 1290:1290
    volumes:
      - ./authentication:/app
    depends_on:
      - db
    environment:
        - DJANGO_SETTINGS_MODULE=authentication.settings_prod
  
  platform-api:
    env_file:
        - .env
    build:
      context: ./platform_api
    ports:
      - 2500:2500
    volumes:
      - ./platform_api:/app
    depends_on:
      - db
    environment:
        - DJANGO_SETTINGS_MODULE=platform_api.settings_prod
  
  transactions:
    env_file:
      - .env
    build:
      context: ./invoice_transactions
    ports:
      - 2950:2950
    volumes:
      - ./invoice_transactions:/app
    depends_on:
      - db
    environment:
        - DJANGO_SETTINGS_MODULE=invoice_transactions.settings_prod

  db:
      image: postgres:alpine
      container_name: postgres_db
      restart: always
      environment:
        POSTGRES_DB: nova_crypto
        POSTGRES_USER: crypto_admin
        POSTGRES_PASSWORD: novacryptotradingplatform
      volumes:
        - postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./shared_config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - platform-api
      - transactions
      - authentication
volumes:
  postgres_data:

