# Generated by Django 4.1 on 2023-07-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='profile_kyc.userprofile'),
            preserve_default=False,
        ),
    ]
