# Generated by Django 4.1 on 2023-07-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_kyc', '0002_kyc_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mailing_address',
            new_name='home_address',
        ),
    ]
