# Generated by Django 4.1.4 on 2023-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_kyc', '0003_rename_mailing_address_userprofile_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='document_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kyc',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identification_documents',
            field=models.FileField(upload_to='documents/identification/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='proof_of_address',
            field=models.FileField(upload_to='documents/proof-of-address/'),
        ),
    ]
