# Generated by Django 4.1.4 on 2023-07-20 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type_of_transaction', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('paid_date_time', models.DateTimeField(blank=True, null=True)),
                ('paid_from', models.CharField(max_length=100)),
                ('payment_destination', models.CharField(max_length=100)),
            ],
        ),
    ]
