# Generated by Django 4.1.4 on 2023-07-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type_of_transaction',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Buy', 'Buy'), ('Sell', 'Sell')], max_length=20),
        ),
    ]
