# Generated by Django 4.1.4 on 2023-07-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='symbol',
            field=models.CharField(default='', max_length=100),
        ),
    ]
